changed colors, fonts, in the news page
CDRH/african_poetics pull request #173
Opened 2021-01-28 22:02 UTC by karindalziel

2021-01-28 22:04 UTC, karindalziel commented on app/assets/stylesheets/bootstrap-variables.scss
> +// Variables
Karin remove this

2021-02-03 18:50 UTC, karindalziel commented on app/assets/stylesheets/bootstrap-variables.scss
I moved these to the _fonts.html.erb template

2021-02-03 18:51 UTC, karindalziel commented on app/assets/stylesheets/bootstrap-variables.scss
>  //== Colors
I move the font call to the _fonts.html.erb template

2021-02-03 19:04 UTC, karindalziel commented on app/views/layouts/body/_title.html.erb
> +  <span class="site-title-container01"></span>
extra spans are there in order to make background colors (different on each side) stretch across all the way

2021-02-03 20:48 UTC, techgique requested changes
Just a couple questions about some changes

2021-02-03 20:48 UTC, techgique commented on app/views/inthenews/home.html.erb
> +<div class="container-fluid home_container inthenews_container">
Can we look at indenting the content inside of these divs to keep the alignment below consistent?

2021-02-03 20:48 UTC, techgique commented on app/views/inthenews/home.html.erb
> +    <%# render "partials/map_africa" %>
Can we remove this since it should be trivial to add back by copying from the other page template?

2021-02-04 15:48 UTC, merged